// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
public class City  : MonoBehaviour
{
	[HideInInspector]
	public int[] costTable = new int[3];
	public int regionID = 0;
	public int effectiveTravelCost = -1;

	[HideInInspector]
	public ArrayList owners = new ArrayList();
	[HideInInspector]
	public ArrayList edges = new ArrayList();

	private Vector3[] objectOffsets = new Vector3[3];

	private TextMesh textMesh = null;
	private GameObject textObj = null;

	public void Start() {
		costTable[0] = 10;
		costTable[1] = 15;
		costTable[2] = 20;

		float offset = 0.075f;
		objectOffsets [0] = new Vector3 (-offset, offset, offset);
		objectOffsets [1] = new Vector3 (0, offset, -offset);
		objectOffsets [2] = new Vector3 (offset, offset, offset);
	}

	public override string ToString() {
		string info;
		info = gameObject.name + " :";
		foreach (Edge e in edges) {
			info += e.cost + " " + e.start.gameObject.name + " " + e.end.gameObject.name;
		}
		return info;
	}

	public bool PlayerIsOwner(Player p){
		foreach (Player o in owners) {
			if(p.gameObject.name == o.gameObject.name)
				return true;
		}
		return false;
	}

	public int Occupancy() {
		return owners.Count;
	}

	public int StepCost(int step) {
		if (owners == null)
			owners = new ArrayList ();

		if (owners.Count >= step)
			return -1;

		step = owners.Count+1;

		return costTable [step - 1];
	}

	public void OnMouseOver() {

		if (GameState.instance.CurrentState != GameState.State.BuildCities)
			return;

		if (textObj == null)
			textObj = GameObject.Find ("CityPopupText");
		if (textMesh == null)
			textMesh = textObj.GetComponent<TextMesh> ();
	

		int effectiveCost = StepCost (GameState.instance.gameStep) + effectiveTravelCost;
		if ((effectiveTravelCost == -1) || (StepCost (GameState.instance.gameStep) == -1)) {
			effectiveCost = -1;
		}
		if (effectiveCost == -1) {
			textObj.transform.position = transform.position + new Vector3(0.3f,0.2f,0);
			textMesh.text = gameObject.name + "\nCost: NA" ;//+ "(" + StepCost (GameState.instance.gameStep) + "," + effectiveTravelCost + ")";
		}
		else {
			textObj.transform.position = transform.position + new Vector3(0.3f, 0.2f,0);
			textMesh.text = gameObject.name + "\nCost: " + effectiveCost;// + "(" + StepCost (GameState.instance.gameStep) + "," + effectiveTravelCost + ")";

		}
		if (Input.GetMouseButtonDown (0)) {

			//current player buys city

			Player p = GameState.instance.CurrentPlayer();
			if(effectiveCost == -1) {
				print (gameObject.name + " is not available to purchase");
			} else if(p.cash >= effectiveCost) {
				GameObject obj = (GameObject)Instantiate(
					GameState.instance.powerPlantObject, 
					transform.position,
					Quaternion.AngleAxis(Random.Range(0.0f,360.0f),Vector3.up));
				obj.transform.position += objectOffsets[owners.Count];

				obj.GetComponent<Renderer>().material.color = p.color;
				obj.SetActive(true);

				owners.Add(p);
				p.cities.Add(this);
				p.cash -= effectiveCost;
				print (p.gameObject.name + " bought " + gameObject.name + " for " + effectiveCost);

				GameState.instance.RecomputeTravelCosts();

			} else {
				print (p.gameObject.name + " does not have enough cash");
			}
		}
	}
}

