// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
public class City  : MonoBehaviour
{
	private int cost1 = 10;
	private int cost2 = 15;
	private int cost3 = 20;
	public int regionID = 0;
	public bool beenVisited = false;

	[HideInInspector]
	public ArrayList owners = new ArrayList();
	public ArrayList edges = new ArrayList();

	public City (string name, int region, GameObject prefab)
	{
		gameObject.name = name;
		regionID = region;
	}

	public override string ToString() {
		string info;
		info = gameObject.name + " :";
		foreach (Edge e in edges) {
			info += e.cost + " " + e.start.gameObject.name + " " + e.end.gameObject.name;
		}
		return info;
	}

	public bool PlayerIsOwner(Player p){
		foreach (Player o in owners) {
			if(p == o)
				return true;
		}
		return false;
	}

	public int Occupancy() {
		return owners.Count;
	}

	public int Cost(int step) {
		if (owners.Count >= step)
			return -1;

		if (owners.Count < step)
			step = owners.Count;

		switch (step) {
		case 1:
			return cost1;
		case 2:
			return cost2;
		default: 
			return cost3;
		}
	}
}

