// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;
using System.Collections;
using System.Collections.Generic;
public class PowerPlant : MonoBehaviour, IComparable
{
	public int baseCost;
	public int power;
	public int materialCost;
	[HideInInspector]
	public int materialStock;

	public Type type;
	
	public enum Type
	{
		Coal,
		Oil,
		Hybrid,
		Garbage,
		Uranium,
		Clean,
		Step3
	};
	
	public int CompareTo( object pp) {
		return baseCost.CompareTo (((PowerPlant)pp).baseCost);
	}
	public PowerPlant (int cost, int power, int materialCount, Type plantType)
	{
		baseCost = cost;
		this.power = power;
		materialCost = materialCount;
		type = plantType;
		materialStock = 0;
	}

	public bool CanStockMoreMaterial() {
		return (materialStock < 2 * materialCost);
	}

	public bool AddMaterial() {
		if (CanStockMoreMaterial ()) {
			materialStock++;
			return true;
		}
		return false;
	}

	public int RunPlant() {
		if(materialCost > materialStock)
			return 0;

		materialStock -= materialCost;
		return power;
	}

	public override string ToString() {
		string info = "cost:" + baseCost + " power:" + power + " materialCost:" + materialCost + " type:" + type;
		return info;
	}

}

