// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
public class PowerPlantMaterialStore
{
	public enum Type {
		Coal,
		Oil,
		Garbage,
		Uranium,
	};
			              
	public int[,] costTable;

	public int[,,] materialRefillTable;
	public int[] inventory = new int[4];
	public int[] inventoryMaximums = new int[4];

	public PowerPlantMaterialStore ()
	{
		inventory [0] = 0;
		inventory [1] = 0;
		inventory [2] = 0;
		inventory [3] = 0;

		inventoryMaximums [(int)Type.Coal] = 24;
		inventoryMaximums [(int)Type.Oil] = 24;
		inventoryMaximums [(int)Type.Garbage] = 24;
		inventoryMaximums [(int)Type.Uranium] = 12;
		InitializeCostTables ();
		InitializeMaterialRefillTable ();
	}

	public void InitializeMaterialRefillTable() {
		materialRefillTable = new int[7, 4, 4];
		//2 players
		materialRefillTable [2, 1, (int)Type.Coal] 		= 3;
		materialRefillTable [2, 1, (int)Type.Oil] 		= 2;
		materialRefillTable [2, 1, (int)Type.Garbage] 	= 1;
		materialRefillTable [2, 1, (int)Type.Uranium] 	= 1;

		materialRefillTable [2, 2, (int)Type.Coal] 		= 4;
		materialRefillTable [2, 2, (int)Type.Oil] 		= 2;
		materialRefillTable [2, 2, (int)Type.Garbage] 	= 2;
		materialRefillTable [2, 2, (int)Type.Uranium] 	= 1;

		materialRefillTable [2, 3, (int)Type.Coal] 		= 3;
		materialRefillTable [2, 3, (int)Type.Oil] 		= 4;
		materialRefillTable [2, 3, (int)Type.Garbage] 	= 3;
		materialRefillTable [2, 3, (int)Type.Uranium] 	= 1;

		//3 players
		materialRefillTable [3, 1, (int)Type.Coal] 		= 4;
		materialRefillTable [3, 1, (int)Type.Oil] 		= 2;
		materialRefillTable [3, 1, (int)Type.Garbage] 	= 1;
		materialRefillTable [3, 1, (int)Type.Uranium] 	= 1;
							 
		materialRefillTable [3, 2, (int)Type.Coal] 		= 5;
		materialRefillTable [3, 2, (int)Type.Oil] 		= 3;
		materialRefillTable [3, 2, (int)Type.Garbage] 	= 2;
		materialRefillTable [3, 2, (int)Type.Uranium] 	= 1;
							 
		materialRefillTable [3, 3, (int)Type.Coal] 		= 3;
		materialRefillTable [3, 3, (int)Type.Oil] 		= 4;
		materialRefillTable [3, 3, (int)Type.Garbage] 	= 3;
		materialRefillTable [3, 3, (int)Type.Uranium] 	= 1;

		//4 players
		materialRefillTable [4, 1, (int)Type.Coal] 		= 5;
		materialRefillTable [4, 1, (int)Type.Oil] 		= 3;
		materialRefillTable [4, 1, (int)Type.Garbage] 	= 2;
		materialRefillTable [4, 1, (int)Type.Uranium] 	= 1;
							 
		materialRefillTable [4, 2, (int)Type.Coal] 		= 6;
		materialRefillTable [4, 2, (int)Type.Oil] 		= 4;
		materialRefillTable [4, 2, (int)Type.Garbage] 	= 3;
		materialRefillTable [4, 2, (int)Type.Uranium] 	= 2;
							 
		materialRefillTable [4, 3, (int)Type.Coal] 		= 4;
		materialRefillTable [4, 3, (int)Type.Oil] 		= 5;
		materialRefillTable [4, 3, (int)Type.Garbage] 	= 4;
		materialRefillTable [4, 3, (int)Type.Uranium] 	= 2;


		//5 players
		materialRefillTable [5, 1, (int)Type.Coal] 		= 5;
		materialRefillTable [5, 1, (int)Type.Oil] 		= 4;
		materialRefillTable [5, 1, (int)Type.Garbage] 	= 3;
		materialRefillTable [5, 1, (int)Type.Uranium] 	= 2;
							 
		materialRefillTable [5, 2, (int)Type.Coal] 		= 7;
		materialRefillTable [5, 2, (int)Type.Oil] 		= 5;
		materialRefillTable [5, 2, (int)Type.Garbage] 	= 3;
		materialRefillTable [5, 2, (int)Type.Uranium] 	= 3;
							 
		materialRefillTable [5, 3, (int)Type.Coal] 		= 5;
		materialRefillTable [5, 3, (int)Type.Oil] 		= 6;
		materialRefillTable [5, 3, (int)Type.Garbage] 	= 5;
		materialRefillTable [5, 3, (int)Type.Uranium] 	= 2;


		//6 players
		materialRefillTable [6, 1, (int)Type.Coal] 		= 7;
		materialRefillTable [6, 1, (int)Type.Oil] 		= 5;
		materialRefillTable [6, 1, (int)Type.Garbage] 	= 3;
		materialRefillTable [6, 1, (int)Type.Uranium] 	= 2;
							 
		materialRefillTable [6, 2, (int)Type.Coal] 		= 9;
		materialRefillTable [6, 2, (int)Type.Oil] 		= 6;
		materialRefillTable [6, 2, (int)Type.Garbage] 	= 5;
		materialRefillTable [6, 2, (int)Type.Uranium] 	= 3;
							 
		materialRefillTable [6, 3, (int)Type.Coal] 		= 6;
		materialRefillTable [6, 3, (int)Type.Oil] 		= 7;
		materialRefillTable [6, 3, (int)Type.Garbage] 	= 6;
		materialRefillTable [6, 3, (int)Type.Uranium] 	= 3;

	}

	public void InitializeCostTables() {
		costTable = new int[4,25];
		//coal, oil, garbage

		costTable [(int)Type.Coal, 0] = 8;
		costTable [(int)Type.Coal, 1] = 8;
		costTable [(int)Type.Coal, 2] = 8;
		costTable [(int)Type.Coal, 3] = 8;
		costTable [(int)Type.Coal, 4] = 7;
		costTable [(int)Type.Coal, 5] = 7;
		costTable [(int)Type.Coal, 6] = 7;
		costTable [(int)Type.Coal, 7] = 6;
		costTable [(int)Type.Coal, 8] = 6;
		costTable [(int)Type.Coal, 9] = 6;
		costTable [(int)Type.Coal, 10] = 5;
		costTable [(int)Type.Coal, 11] = 5;
		costTable [(int)Type.Coal, 12] = 5;
		costTable [(int)Type.Coal, 13] = 4;
		costTable [(int)Type.Coal, 14] = 4;
		costTable [(int)Type.Coal, 15] = 4;
		costTable [(int)Type.Coal, 16] = 3;
		costTable [(int)Type.Coal, 17] = 3;
		costTable [(int)Type.Coal, 18] = 3;
		costTable [(int)Type.Coal, 19] = 2;
		costTable [(int)Type.Coal, 20] = 2;
		costTable [(int)Type.Coal, 21] = 2;
		costTable [(int)Type.Coal, 22] = 1;
		costTable [(int)Type.Coal, 23] = 1;
		costTable [(int)Type.Coal, 24] = 1;

		costTable [(int)Type.Oil, 0] = 8;
		costTable [(int)Type.Oil, 1] = 8;
		costTable [(int)Type.Oil, 2] = 8;
		costTable [(int)Type.Oil, 3] = 8;
		costTable [(int)Type.Oil, 4] = 7;
		costTable [(int)Type.Oil, 5] = 7;
		costTable [(int)Type.Oil, 6] = 7;
		costTable [(int)Type.Oil, 7] = 6;
		costTable [(int)Type.Oil, 8] = 6;
		costTable [(int)Type.Oil, 9] = 6;
		costTable [(int)Type.Oil, 10] = 5;
		costTable [(int)Type.Oil, 11] = 5;
		costTable [(int)Type.Oil, 12] = 5;
		costTable [(int)Type.Oil, 13] = 4;
		costTable [(int)Type.Oil, 14] = 4;
		costTable [(int)Type.Oil, 15] = 4;
		costTable [(int)Type.Oil, 16] = 3;
		costTable [(int)Type.Oil, 17] = 3;
		costTable [(int)Type.Oil, 18] = 3;
		costTable [(int)Type.Oil, 19] = 2;
		costTable [(int)Type.Oil, 20] = 2;
		costTable [(int)Type.Oil, 21] = 2;
		costTable [(int)Type.Oil, 22] = 1;
		costTable [(int)Type.Oil, 23] = 1;
		costTable [(int)Type.Oil, 24] = 1;

		costTable [(int)Type.Garbage, 0] = 8;
		costTable [(int)Type.Garbage, 1] = 8;
		costTable [(int)Type.Garbage, 2] = 8;
		costTable [(int)Type.Garbage, 3] = 8;
		costTable [(int)Type.Garbage, 4] = 7;
		costTable [(int)Type.Garbage, 5] = 7;
		costTable [(int)Type.Garbage, 6] = 7;
		costTable [(int)Type.Garbage, 7] = 6;
		costTable [(int)Type.Garbage, 8] = 6;
		costTable [(int)Type.Garbage, 9] = 6;
		costTable [(int)Type.Garbage, 10] = 5;
		costTable [(int)Type.Garbage, 11] = 5;
		costTable [(int)Type.Garbage, 12] = 5;
		costTable [(int)Type.Garbage, 13] = 4;
		costTable [(int)Type.Garbage, 14] = 4;
		costTable [(int)Type.Garbage, 15] = 4;
		costTable [(int)Type.Garbage, 16] = 3;
		costTable [(int)Type.Garbage, 17] = 3;
		costTable [(int)Type.Garbage, 18] = 3;
		costTable [(int)Type.Garbage, 19] = 2;
		costTable [(int)Type.Garbage, 20] = 2;
		costTable [(int)Type.Garbage, 21] = 2;
		costTable [(int)Type.Garbage, 22] = 1;
		costTable [(int)Type.Garbage, 23] = 1;
		costTable [(int)Type.Garbage, 24] = 1;

		costTable [(int)Type.Uranium, 0] = 16;
		costTable [(int)Type.Uranium, 1] = 16;
		costTable [(int)Type.Uranium, 2] = 14;
		costTable [(int)Type.Uranium, 3] = 12;
		costTable [(int)Type.Uranium, 4] = 10;
		costTable [(int)Type.Uranium, 5] = 8;
		costTable [(int)Type.Uranium, 6] = 7;
		costTable [(int)Type.Uranium, 7] = 6;
		costTable [(int)Type.Uranium, 8] = 5;
		costTable [(int)Type.Uranium, 9] = 4;
		costTable [(int)Type.Uranium, 10] = 3;
		costTable [(int)Type.Uranium, 11] = 2;
		costTable [(int)Type.Uranium, 12] = 1;
		costTable [(int)Type.Uranium, 13] = 1;
		costTable [(int)Type.Uranium, 14] = 1;
		costTable [(int)Type.Uranium, 15] = 1;
		costTable [(int)Type.Uranium, 16] = 1;
		costTable [(int)Type.Uranium, 17] = 1;
		costTable [(int)Type.Uranium, 18] = 1;
		costTable [(int)Type.Uranium, 19] = 1;
		costTable [(int)Type.Uranium, 20] = 1;
		costTable [(int)Type.Uranium, 21] = 1;
		costTable [(int)Type.Uranium, 22] = 1;
		costTable [(int)Type.Uranium, 23] = 1;
		costTable [(int)Type.Uranium, 24] = 1;
	}

	public void Restock(int playerCount, int step) {

		Stock (Type.Coal, materialRefillTable [playerCount, step, (int)Type.Coal]);
		Stock (Type.Oil, materialRefillTable [playerCount, step, (int)Type.Oil]);
		Stock (Type.Garbage, materialRefillTable [playerCount, step, (int)Type.Garbage]);
		Stock (Type.Uranium, materialRefillTable [playerCount, step, (int)Type.Uranium]);
	}

	public void Stock(PowerPlantMaterialStore.Type type, int count) {

		//should take into account unit owned by players?

		inventory[(int)type] += count;
		if (inventory [(int)type] > inventoryMaximums [(int)type])
			inventory [(int)type] = inventoryMaximums [(int)type];
		if (inventory [(int)type] < 0)
			inventory [(int)type] = 0;
	}

	public int QueryInventory(PowerPlantMaterialStore.Type type) {
		return inventory [(int)type];
	}

	public int QueryCost(PowerPlantMaterialStore.Type type) {
		return costTable[(int)type, QueryInventory(type)];
	}


	public bool Take(PowerPlantMaterialStore.Type type, int count) {
		if (inventory [(int)type] < count)
			return false;
	
		inventory [(int)type] -= count;
		return true;
	}
}

